FROM python:3.11-bullseye

RUN pip install poetry==2.1.2

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /home/govscape
WORKDIR /home/govscape
COPY . .

EXPOSE 8080

RUN poetry install

ENTRYPOINT ["poetry", "run", "python",  "scripts/run_embedding_pipeline.py"]
