[pytest]
addopts = --mypy
filterwarnings =
    ignore::PendingDeprecationWarning

    # The combination of pylucene 10.0.0 and python 3.11.14 likes to emit warnings.
    # These warnings do not affect functionality, but they do pollute the test output.
    ignore:builtin type .* has no __module__ attribute:DeprecationWarning
testpaths =
    govscape/tests
junit_family=xunit2
xfail_strict=true
