defaults:
      run:
        shell: bash -el {0}

name: CI
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.11.14']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    container:
      # TODO, once first PR is merged, update to use proper version tag instead of sha for the base image
      image: ghcr.io/bcglee/govscape-base:sha-fa1467e
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Install packages
        run: |
          poetry install
      - name: Run tests
        run: |
          poetry run pytest govscape/tests
      - uses: codecov/codecov-action@v5

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
