name: Publish Base Image

on:
  push:
    branches: ["**"]
    paths:
      - .github/workflows/publish-base-image.yml
      - docker/images/govscape-base/Dockerfile
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-base-image-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python_version: 3.11.14
            lucene_version: 10.0.0
            poetry_version: 2.3.2
            # Obtain checksum from https://dlcdn.apache.org/lucene/pylucene/
            lucene_sha256: "100c3d61d6799ac16b7b8c1826cddf07fb1715141ebdb0d7b8119cdd96b24574  pylucene-10.0.0-src.tar.gz"

          # Add more versions below as needed.

          # - python_version:
          #   lucene_version:
          #   poetry_version:
          #   lucene_sha256: ""


    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/govscape-base
          tags: |
            type=sha,prefix=sha-
            type=raw,value=py${{ matrix.python_version }}-lucene${{ matrix.lucene_version }}-poetry${{ matrix.poetry_version }},enable={{is_default_branch}}
            type=ref,event=branch,prefix=py${{ matrix.python_version }}-lucene${{ matrix.lucene_version }}-poetry${{ matrix.poetry_version }}-
          labels: |
            org.opencontainers.image.title=GovScape Base Image
            org.opencontainers.image.description=Base Docker image for GovScape, containing Python, Lucene, and Poetry.

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker/images/govscape-base
          file: docker/images/govscape-base/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}-trixie
            LUCENE_VERSION=${{ matrix.lucene_version }}
            LUCENE_SHA256=${{ matrix.lucene_sha256 }}
            POETRY_VERSION=${{ matrix.poetry_version }}
